import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: { translation: { Language: 'Language', Save: 'Save', 'Account Settings': 'Account Settings', Dashboard: 'Dashboard', 'Logged Out': 'Logged Out', 'You have been successfully logged out.': 'You have been successfully logged out.', 'Logout Failed': 'Logout Failed', 'Failed to log out. Please try again.': 'Failed to log out. Please try again.', 'Log Out': 'Log Out', 'Sign In': 'Sign In', 'Get Started': 'Get Started', Home: 'Home', Trading: 'Trading', Arbitrage: 'Arbitrage', Wallet: 'Wallet', Portfolio: 'Portfolio', Account: 'Account' } },
  zh: { translation: { Language: '語言', Save: '保存', 'Account Settings': '账户设置', Dashboard: '仪表盘', 'Logged Out': '已登出', 'You have been successfully logged out.': '您已成功登出。', 'Logout Failed': '登出失败', 'Failed to log out. Please try again.': '登出失败，请重试。', 'Log Out': '登出', 'Sign In': '登录', 'Get Started': '开始', Home: '首页', Trading: '交易', Arbitrage: '套利', Wallet: '钱包', Portfolio: '投资组合', Account: '账户' } },
  hi: { translation: { Language: 'भाषा', Save: 'सहेजें', 'Account Settings': 'खाता सेटिंग्स', Dashboard: 'डैशबोर्ड', 'Logged Out': 'लॉग आउट', 'You have been successfully logged out.': 'आप सफलतापूर्वक लॉग आउट हो गए हैं।', 'Logout Failed': 'लॉग आउट विफल', 'Failed to log out. Please try again.': 'लॉग आउट विफल रहा। कृपया पुनः प्रयास करें।', 'Log Out': 'लॉग आउट', 'Sign In': 'साइन इन करें', 'Get Started': 'शुरू करें', Home: 'होम', Trading: 'ट्रेडिंग', Arbitrage: 'आर्बिट्राज', Wallet: 'वॉलेट', Portfolio: 'पोर्टफोलियो', Account: 'खाता' } },
  es: { translation: { Language: 'Idioma', Save: 'Guardar', 'Account Settings': 'Configuración de cuenta', Dashboard: 'Panel', 'Logged Out': 'Desconectado', 'You have been successfully logged out.': 'Has cerrado sesión correctamente.', 'Logout Failed': 'Error al cerrar sesión', 'Failed to log out. Please try again.': 'No se pudo cerrar sesión. Inténtalo de nuevo.', 'Log Out': 'Cerrar sesión', 'Sign In': 'Iniciar sesión', 'Get Started': 'Comenzar', Home: 'Inicio', Trading: 'Comercio', Arbitrage: 'Arbitraje', Wallet: 'Billetera', Portfolio: 'Portafolio', Account: 'Cuenta' } },
  fr: { translation: { Language: 'Langue', Save: 'Enregistrer', 'Account Settings': 'Paramètres du compte', Dashboard: 'Tableau de bord', 'Logged Out': 'Déconnecté', 'You have been successfully logged out.': 'Vous vous êtes déconnecté avec succès.', 'Logout Failed': 'Échec de la déconnexion', 'Failed to log out. Please try again.': 'Échec de la déconnexion. Veuillez réessayer.', 'Log Out': 'Déconnexion', 'Sign In': 'Se connecter', 'Get Started': 'Commencer', Home: 'Accueil', Trading: 'Trading', Arbitrage: 'Arbitrage', Wallet: 'Portefeuille', Portfolio: 'Portefeuille', Account: 'Compte' } },
  ar: { translation: { Language: 'اللغة', Save: 'حفظ', 'Account Settings': 'إعدادات الحساب', Dashboard: 'لوحة القيادة', 'Logged Out': 'تم تسجيل الخروج', 'You have been successfully logged out.': 'تم تسجيل خروجك بنجاح.', 'Logout Failed': 'فشل تسجيل الخروج', 'Failed to log out. Please try again.': 'فشل تسجيل الخروج. حاول مرة أخرى.', 'Log Out': 'تسجيل الخروج', 'Sign In': 'تسجيل الدخول', 'Get Started': 'ابدأ', Home: 'الرئيسية', Trading: 'تداول', Arbitrage: 'المراجحة', Wallet: 'محفظة', Portfolio: 'محفظة استثمارية', Account: 'الحساب' } },
  bn: { translation: { Language: 'ভাষা', Save: 'সংরক্ষণ করুন', 'Account Settings': 'অ্যাকাউন্ট সেটিংস', Dashboard: 'ড্যাশবোর্ড', 'Logged Out': 'লগ আউট', 'You have been successfully logged out.': 'আপনি সফলভাবে লগ আউট হয়েছেন।', 'Logout Failed': 'লগ আউট ব্যর্থ', 'Failed to log out. Please try again.': 'লগ আউট ব্যর্থ হয়েছে। আবার চেষ্টা করুন।', 'Log Out': 'লগ আউট', 'Sign In': 'সাইন ইন', 'Get Started': 'শুরু করুন', Home: 'হোম', Trading: 'ট্রেডিং', Arbitrage: 'আর্বিট্রেজ', Wallet: 'ওয়ালেট', Portfolio: 'পোর্টফোলিও', Account: 'অ্যাকাউন্ট' } },
  pt: { translation: { Language: 'Idioma', Save: 'Salvar', 'Account Settings': 'Configurações da conta', Dashboard: 'Painel', 'Logged Out': 'Desconectado', 'You have been successfully logged out.': 'Você saiu com sucesso.', 'Logout Failed': 'Falha ao sair', 'Failed to log out. Please try again.': 'Falha ao sair. Por favor, tente novamente.', 'Log Out': 'Sair', 'Sign In': 'Entrar', 'Get Started': 'Começar', Home: 'Início', Trading: 'Negociação', Arbitrage: 'Arbitragem', Wallet: 'Carteira', Portfolio: 'Portfólio', Account: 'Conta' } },
  ru: { translation: { Language: 'Язык', Save: 'Сохранить', 'Account Settings': 'Настройки аккаунта', Dashboard: 'Панель управления', 'Logged Out': 'Вышли из системы', 'You have been successfully logged out.': 'Вы успешно вышли из системы.', 'Logout Failed': 'Ошибка выхода', 'Failed to log out. Please try again.': 'Не удалось выйти. Пожалуйста, попробуйте еще раз.', 'Log Out': 'Выйти', 'Sign In': 'Войти', 'Get Started': 'Начать', Home: 'Главная', Trading: 'Торговля', Arbitrage: 'Арбитраж', Wallet: 'Кошелек', Portfolio: 'Портфель', Account: 'Аккаунт' } },
  ur: { translation: { Language: 'زبان', Save: 'محفوظ کریں', 'Account Settings': 'اکاؤنٹ کی ترتیبات', Dashboard: 'ڈیش بورڈ', 'Logged Out': 'لاگ آؤٹ', 'You have been successfully logged out.': 'آپ کامیابی سے لاگ آؤٹ ہو گئے ہیں۔', 'Logout Failed': 'لاگ آؤٹ ناکام', 'Failed to log out. Please try again.': 'لاگ آؤٹ ناکام۔ دوبارہ کوشش کریں۔', 'Log Out': 'لاگ آؤٹ', 'Sign In': 'سائن ان کریں', 'Get Started': 'شروع کریں', Home: 'ہوم', Trading: 'ٹریڈنگ', Arbitrage: 'آربیٹریج', Wallet: 'والیٹ', Portfolio: 'پورٹ فولیو', Account: 'اکاؤنٹ' } },
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: localStorage.getItem('language') || 'en',
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
  });

export default i18n; 